# https://man.sr.ht/tutorials/getting-started-with-builds.md
# https://git.sr.ht/~sircmpwn/scdoc/tree/master/.build.yml

image: debian/stable
packages:
  - flex
  - bison
  - curl
sources:
  - https://git.sr.ht/~moteta/libforks
  - https://git.sr.ht/~sircmpwn/annotatec
secrets:
  - f21baa04-0d45-473e-b6f4-d431c55b358c # ~/upload-annotations
tasks:
  - build_and_test: |
      cd libforks
      export CFLAGS="-fsanitize=address"
      ./build.sh

  - annotatec: |
      cd annotatec
      make
      sudo make install PREFIX=/usr

  - annotations: |
      cd ~/libforks
      annotatec -gC 'cpp -std=c99 -I.' \
        libforks.c \
        >annotations.json
      ~/upload-annotations annotations.json moteta libforks

